services:
  #ELK: elasticsearch, logstash, kibana
  elasticsearch:
    image: elasticsearch:9.2.3
    container_name: elasticsearch
    ports: 
      - 9200:9200
    environment:
      - xpack.security.enabled=false # Disable security for local development
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:9.2.3
    ports:
      - 5601:5601
  logstash:
    image: logstash:9.2.3
    container_name: logstash
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
        